### ISSUE TITLE
Unable to install dotnet-sdk on Ubuntu 17.10

### ISSUE THREAD

**Issue by PabloRioseco** [dotnet/core#1450]
I am trying to install dotnet-sdk to then be able to work with Visual Studio Code with dotnet in ubuntu 17.10

S.O.: Ubuntu 17.10 64b
Update: Lastest version.

I am performing the following procedure indicated by: https://www.microsoft.com/net/learn/get-started/linux/ubuntu17-10
but when I'm installed sdk, I get an error when installing dotnet-sdk:

`sudo apt-get install apt-transport-https` 
`sudo apt-get update`

`sudo apt-get install dotnet-sdk-2.1.104`
```
Reading list of packages ... Done
Creating dependency tree
Reading the status information ... Done
Do not can instal some pack. This may mean that
you asked for an impossible situation or, if you are using the distribution
unstable, that some necessary packages have not yet been created or are
They have taken out of «Incoming».
The following information can help resolve the situation:

The following packages have unfulfilled dependencies:
  dotnet-sdk-2.1.104: It depends: dotnet-runtime-2.0.6 but it will not be installed
E: Problems could not be corrected, you have retained broken packages.
```

**Comment by richlander** [comment]
PTAL @leecow

**Comment by leecow** [comment]
I've confirmed the 17.10 repo is working correctly and was able to install dotnet-sdk-2.1.104 (we released [2.1.105](https://github.com/dotnet/core/issues/1456) today). It may be that you need to do a little house cleaning. The easiest first step is to `sudo apt-get remove dotnet-host`. This will uninstall the host and all dependencies leaving you in a fairly clean state to try in re-install.

**Comment by Mayocampo** [comment]
Hi @leecow , i have the same issue trying to install 2.1.105. Already executed `sudo apt-get remove dotnet-host` but error still there... What other steps can we follow to install core 2.0 ?

(im doing this process in order to install JetBrains Rider)

**Comment by Mayocampo** [comment]
Followed instructions here
[](https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.7-download.md)

And still not working

![screenshot-2018-04-19 15-42-24](https://user-images.githubusercontent.com/22798602/39017297-814f79d6-43e8-11e8-82e4-5421f029c0dc.png)

**Comment by Mayocampo** [comment]
Also tried to install only dotnet-runtime-2.0.7 and get this error

```
may@maylinux ~ $ sudo apt-get install dotnet-runtime-2.0.7
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
No se pudieron instalar algunos paquetes. Esto puede significar que
usted pidió una situación imposible o, si está usando la distribución
inestable, que algunos paquetes necesarios aún no se han creado o se
han sacado de «Incoming».
La siguiente información puede ayudar a resolver la situación:

Los siguientes paquetes tienen dependencias incumplidas:
 dotnet-runtime-2.0.7 : Depende: libgssapi-krb5-2 (>= 1.14+dfsg) pero 1.13.2+dfsg-5ubuntu2 va a ser instalado
                        Depende: libicu57 pero no es instalable
                        Depende: dotnet-hostfxr-2.0.7 pero no va a instalarse
E: No se pudieron corregir los problemas, usted ha retenido paquetes rotos.
```
So, in english it says that: 
2.0.7 depends on libgssapi-krb5-2 (>= 1.14+dfsg) but 1.13.2+dfsg-5ubuntu2 will be installed
2.0.7 depends on libicu57 but it's not installable (?)
2.07 depends on  dotnet-hostfxr-2.0.7 but it will be not installed...

So.... whats happening here?

**Comment by Petermarcu** [comment]
Issue moved to [dotnet/core-setup #4049](https://github.com/dotnet/core-setup/issues/4049) via [**ZenHub**](https://www.zenhub.com/)
