### ISSUE TITLE
release.json is incorrect for sdk 2.1.302

### ISSUE THREAD

**Issue by kdubau** [dotnet/core#1775]
This line here: https://github.com/dotnet/core/blob/master/release-notes/releases.json#L25 - from all previous releases, and other files, this line should be only the file name, not a full path. 

It is causing issues on macOS when using the DotNetCoreInstaller task (https://github.com/Microsoft/vsts-tasks/tree/b7244f9d952f36690fcb7792b56fd7d9e3eaf58e/Tasks/DotNetCoreInstallerV0):

>2018-07-11T15:29:59.0621360Z ##[warning]Could not download installation package from this URL: https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.1.302/https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.1.302/dotnet-sdk-2.1.302-osx-x64.tar.gz Error: {}

**Comment by Petermarcu** [comment]
Talked to @leecow and there was a challenge with releasing some of the content to the normal place so the ones with url's are the ones in different locations.

**Comment by leecow** [comment]
Fixed by https://github.com/dotnet/core/pull/1789

@kdubau - There is a significant (ie, breaking) change coming to the metadata format probably with the August release.. Have a look at https://github.com/dotnet/core/blob/master/release-notes/releases-v2.json.

**Comment by kdubau** [comment]
@leecow thanks for the information, I've opened a issues for the vsts-tasks team to track the upcoming change: https://github.com/Microsoft/vsts-tasks/issues/7754

**Comment by bishal-pdMSFT** [comment]
@leecow I don't see the releases-v2.json file at the above link. Is v2 still happening?

**Comment by leecow** [comment]
Yes it is. Work is in the new-json branch and PR (https://github.com/dotnet/core/pull/1960) is out for review right now. Plan to have it merged to master by end of week.
