### ISSUE TITLE
Ubuntu repositories broken

### ISSUE THREAD

**Issue by stefanjarina** [dotnet/core#6381]
Hello,

Ubuntu repositories seems to be broken, specifically I am getting '404 not found' for any .deb

from `apt update`

```
Err:1 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 dotnet-host amd64 5.0.7-1
  404  Not Found [IP: 104.214.230.139 443]
Err:2 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 dotnet-hostfxr-3.1 amd64 3.1.16-1
  404  Not Found [IP: 104.214.230.139 443]
Err:3 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 dotnet-runtime-deps-3.1 amd64 3.1.16-1
  404  Not Found [IP: 104.214.230.139 443]
Err:4 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 dotnet-runtime-3.1 amd64 3.1.16-1
  404  Not Found [IP: 104.214.230.139 443]
Err:5 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 aspnetcore-runtime-3.1 amd64 3.1.16-1
  404  Not Found [IP: 104.214.230.139 443]
Err:6 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 dotnet-apphost-pack-3.1 amd64 3.1.16-1
  404  Not Found [IP: 104.214.230.139 443]
Err:7 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 dotnet-sdk-3.1 amd64 3.1.410-1
  404  Not Found [IP: 104.214.230.139 443]
E: Failed to fetch https://packages.microsoft.com/ubuntu/20.04/prod/pool/main/d/dotnet-host/dotnet-host-5.0.7-x64.deb  404  Not Found [IP: 104.214.230.139 443]
E: Failed to fetch https://packages.microsoft.com/ubuntu/20.04/prod/pool/main/d/dotnet-hostfxr-3.1/dotnet-hostfxr-3.1.16-x64.deb  404  Not Found [IP: 104.214.230.139 443]
E: Failed to fetch https://packages.microsoft.com/ubuntu/20.04/prod/pool/main/d/dotnet-runtime-deps-3.1/dotnet-runtime-deps-3.1.16-x64.deb  404  Not Found [IP: 104.214.230.139 443]
E: Failed to fetch https://packages.microsoft.com/ubuntu/20.04/prod/pool/main/d/dotnet-runtime-3.1/dotnet-runtime-3.1.16-x64.deb  404  Not Found [IP: 104.214.230.139 443]
E: Failed to fetch https://packages.microsoft.com/ubuntu/20.04/prod/pool/main/a/aspnetcore-runtime-3.1/aspnetcore-runtime-3.1.16-x64.deb  404  Not Found [IP: 104.214.230.139 443]
E: Failed to fetch https://packages.microsoft.com/ubuntu/20.04/prod/pool/main/d/dotnet-apphost-pack-3.1/dotnet-apphost-pack-3.1.16-x64.deb  404  Not Found [IP: 104.214.230.139 443]
E: Failed to fetch https://packages.microsoft.com/ubuntu/20.04/prod/pool/main/d/dotnet-sdk-3.1/dotnet-sdk-3.1.410-x64.deb  404  Not Found [IP: 104.214.230.139 443]
```

Tried to re-download the repository package, however it seems to be simply not there:

```bash
~> wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
--2021-06-16 22:40:24--  https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
Resolving packages.microsoft.com (packages.microsoft.com)... 13.80.99.124
Connecting to packages.microsoft.com (packages.microsoft.com)|13.80.99.124|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-06-16 22:40:24 ERROR 404: Not Found.
```

This issue seems to be there only for .deb files though, as others can be downloaded without issues, e.g.

```bash
~> wget https://packages.microsoft.com/config/ubuntu/20.04/mssql-server-2019.list -O mssql-server-2019.list
--2021-06-16 22:52:28--  https://packages.microsoft.com/config/ubuntu/20.04/mssql-server-2019.list
Resolving packages.microsoft.com (packages.microsoft.com)... 40.114.136.21
Connecting to packages.microsoft.com (packages.microsoft.com)|40.114.136.21|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 101 [application/octet-stream]
Saving to: ‘mssql-server-2019.list’

mssql-server-2019.list        100%[=================================================>]     101  --.-KB/s    in 0s

2021-06-16 22:52:28 (29.2 MB/s) - ‘mssql-server-2019.list’ saved [101/101]

~> cat mssql-server-2019.list
deb [arch=amd64,armhf,arm64] https://packages.microsoft.com/ubuntu/20.04/mssql-server-2019 focal main
```

This is true for ALL Ubuntu versions

**Comment by bquantump** [comment]
Broken here too

 wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
--2021-06-16 20:58:37--  https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
Resolving packages.microsoft.com (packages.microsoft.com)... 13.66.21.183
Connecting to packages.microsoft.com (packages.microsoft.com)|13.66.21.183|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
****

**Comment by charliemenke** [comment]
Seeing similar issue for:
Failed to fetch https://packages.microsoft.com/debian/10/prod/pool/main/m/msodbcsql17/msodbcsql17_17.7.2.1-1_amd64.deb  404  Not Found [IP: 13.84.47.71 443]

**Comment by akiehl2000** [comment]
Same here:
<img width="1228" alt="Screen Shot 2021-06-16 at 4 19 58 PM" src="https://user-images.githubusercontent.com/20071048/122302056-d1914a00-cebe-11eb-8d78-982d1453717e.png">

**Comment by michaelgsharp** [comment]
@rbhanda are you able to help here? This seems similar to the situation we saw the other day #6371

**Comment by rbhanda** [comment]
Thanks for letting me @michaelgsharp . I am following up on this with our infrastructure team.

**Comment by rbhanda** [comment]
Update: Our infra team is working on this. There is an issue with some of the mirrors on packages.microsoft.com so as per them, the current ETA to resolve this issue is in next two hours or so.

**Comment by SudhirNune** [comment]
@rbhanda - can you please provide me an update ?

**Comment by iamCristYe** [comment]
https://github.com/microsoft/vscode/issues/126543

**Comment by rbhanda** [comment]
Update: our infra team is still working to resolve this issue. They ran into some space issues but this issue should be resolved quickly. Unfortunately, I do not have an ETA yet.

**Comment by kitsuyui** [comment]
I also understand this is little-bit off-topic for this project.

But let me just say this; I think the problem is not only package repository was broken. Another side of the problem is about communication.

It might be there some progresses on some task tracking system ore some collaboration tools at Microsoft. But we can't see it.

Following issues were opened and some issues were closed so quickly. 
It doesn't show somewhere to go. It doesn't show how long we must wait.
So issues are opened repeatedly here and there. This is spreading between projects outside of Microsoft.

- https://github.com/MicrosoftDocs/sql-docs/issues/6495
- https://github.com/MicrosoftDocs/sql-docs/issues/6494
- https://github.com/dotnet/core/issues/6381
- https://github.com/microsoft/msphpsql/issues/1271
- https://github.com/microsoft/vscode/issues/126543
- https://github.com/mkleehammer/pyodbc/issues/914

**Comment by Niek** [comment]
FYI the Edge repo is broken as well, the whole pool directory is gone: https://packages.microsoft.com/repos/edge/pool/

**Comment by phknot** [comment]
> FYI the Edge repo is broken as well, the whole pool directory is gone: https://packages.microsoft.com/repos/edge/pool/

Same problem for the Teams repo

**Comment by gdams** [comment]
We've also had the bug raised against our Microsoft build of OpenJDK repo https://github.com/microsoft/openjdk/discussions/74

**Comment by p--b** [comment]
This of course affects everyone who uses GitHub Actions' Ubuntu image and hasn't already binned off any repositories that include the word "microsoft" (that are included by default) in their apt config as part of their pipeline.

@kitsuyui is correct that the communication from MS/GH around reliability of these servers is somewhat lacking. To add to the list of knock-on issues, a while ago I filed https://github.com/actions/virtual-environments/issues/3410 when unavailability of these servers last bit me, but GitHub's response was (somewhat amazingly) basically not our problem, wontfix.

**Comment by r3volver** [comment]
I can confirm this issue. 404 in every debian or ubuntu .deb I search.

In the meantime, is there a mirror where we could find the packages?

`Get:1 http://deb.debian.org/debian buster/main amd64 multiarch-support amd64 2.28-10 [215 kB]
Ign:2 https://packages.microsoft.com/debian/10/prod buster/main amd64 odbcinst amd64 2.3.7
Ign:3 https://packages.microsoft.com/debian/10/prod buster/main amd64 unixodbc-dev amd64 2.3.7
Ign:4 https://packages.microsoft.com/debian/10/prod buster/main amd64 odbcinst1debian2 amd64 2.3.7
Ign:5 https://packages.microsoft.com/debian/10/prod buster/main amd64 libodbc1 amd64 2.3.7
Ign:6 https://packages.microsoft.com/debian/10/prod buster/main amd64 unixodbc amd64 2.3.7
Err:7 https://packages.microsoft.com/debian/10/prod buster/main amd64 msodbcsql17 amd64 17.7.2.1-1
  404  Not Found [IP: 40.114.136.21 443]
Err:2 https://packages.microsoft.com/debian/10/prod buster/main amd64 odbcinst amd64 2.3.7
  404  Not Found [IP: 40.114.136.21 443]
Err:3 https://packages.microsoft.com/debian/10/prod buster/main amd64 unixodbc-dev amd64 2.3.7
  404  Not Found [IP: 40.114.136.21 443]
Err:4 https://packages.microsoft.com/debian/10/prod buster/main amd64 odbcinst1debian2 amd64 2.3.7
  404  Not Found [IP: 40.114.136.21 443]
Err:5 https://packages.microsoft.com/debian/10/prod buster/main amd64 libodbc1 amd64 2.3.7
  404  Not Found [IP: 40.114.136.21 443]
Err:6 https://packages.microsoft.com/debian/10/prod buster/main amd64 unixodbc amd64 2.3.7
  404  Not Found [IP: 40.114.136.21 443]
Fetched 215 kB in 1s (373 kB/s)
Unable to correct missing packages.
E: Failed to fetch https://packages.microsoft.com/ubuntu/16.04/prod/pool/main/u/unixodbc/odbcinst_2.3.7_amd64.deb  404  Not Found [IP: 40.114.136.21 443]
E: Failed to fetch https://packages.microsoft.com/ubuntu/16.04/prod/pool/main/u/unixodbc/unixodbc-dev_2.3.7_amd64.deb  404  Not Found [IP: 40.114.136.21 443]
E: Failed to fetch https://packages.microsoft.com/ubuntu/16.04/prod/pool/main/u/unixodbc/odbcinst1debian2_2.3.7_amd64.deb  404  Not Found [IP: 40.114.136.21 443]
E: Failed to fetch https://packages.microsoft.com/ubuntu/16.04/prod/pool/main/u/unixodbc/libodbc1_2.3.7_amd64.deb  404  Not Found [IP: 40.114.136.21 443]
E: Failed to fetch https://packages.microsoft.com/ubuntu/16.04/prod/pool/main/u/unixodbc/unixodbc_2.3.7_amd64.deb  404  Not Found [IP: 40.114.136.21 443]
E: Failed to fetch https://packages.microsoft.com/debian/10/prod/pool/main/m/msodbcsql17/msodbcsql17_17.7.2.1-1_amd64.deb  404  Not Found [IP: 40.114.136.21 443]
E: Aborting install.`

**Comment by hussaynv** [comment]
Some people suggesting its an issue isolated to Europe, other regions as able to build
https://docs.microsoft.com/en-us/answers/questions/439491/pyodbc-install-error-in-azure-databricks-file-not.html

**Comment by sciyako** [comment]
14 hours! this is blocking us in the production environment right now. as we can't build new machines/vms in Azure.

**Comment by GiaNTizmO** [comment]
same too with Debain10 and Ubuntu 20.04LTS

**Comment by chelnak** [comment]
Same here - this is going to be a killer

**Comment by gmemstr** [comment]
Might be worth holding off on the "me too!" or "+1" comments unless there's some new information to make the issue easier to follow.

**Comment by Albonycal** [comment]
Space issues?
LOL

**Comment by tomas-forsman** [comment]
Ask Bill to buy some disks from Amazon :-P

**Comment by SudhirNune** [comment]
I started seeing issue with  **Certificates** (https://packages.microsoft.com/keys/microsoft.asc) too

**Comment by Anmol007** [comment]
I can confirm this issue too. We noticed this today morning and the releases are blocked because of this. 

command in DockerFile:
`RUN apt-get update && apt-get install -y --no-install-recommends \ 
    g++ \
    unixodbc-dev `
    
  Error in azure pipelines:
`Err:1 https://packages.microsoft.com/debian/9/prod stretch/main amd64 unixodbc-dev amd64 2.3.7
  404  Not Found [IP: 137.135.134.16 443]`
`E: Failed to fetch https://packages.microsoft.com/debian/9/prod/pool/main/u/unixodbc/unixodbc-dev_2.3.7_amd64.deb  404  Not Found [IP: 137.135.134.16 443]`

**Comment by aashu-kumari-by** [comment]
I have also started seeing this issue from 17th june morning IST timezone, 
Need to get 210 MB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://packages.microsoft.com/repos/microsoft-ubuntu-focal-prod focal/main amd64 azure-functions-core-tools-3 amd64 3.0.3568-1 [210 MB]
It has got stuck here and not able to get the response. Kindly help in resolving the issue.

**Comment by m17kea** [comment]
@rbhanda any update on this, this is blocking production server builds for us

**Comment by SudhirNune** [comment]
@rbhanda  - its same here and I hope a lot of processes / projects are impacted, is there any update ETA, and any MSFT official status page having the details and update ?

**Comment by AymanAlneser** [comment]
any updates on this
this is affecting Production environment and we need some ETA to communicate to our Stack holders

**Comment by rvResolving** [comment]
for people who need, snap installation is working, i know it is not apt but it can be a temporary solution

**Comment by Kyle2123** [comment]
14 hours later and this is still broken - prevents rolling new builds.  Can we get an update on this please???

**Comment by tappoz** [comment]
> for people who need, snap installation is working, i know it is not apt but it can be a temporary solution

@rvResolving can you please provide some context with commands around what works for you?

I am using the `apt` repositories (on Debian) for the SQL Server integration, so I tried this:

```
snap find microsoft | grep -e msodbcsql17 -e mssql-tools -e unixodbc-dev
```

It does not find anything

**Comment by coding-liki** [comment]
All deb-based repos at packages.microsoft.com are broken. I suggest, that they hid the "pool" folder for some reason.

**Comment by rpyndus** [comment]
I tried to use proxy in US, but unfortunately no success in doing that, pool folder does not exists. Also snap wont help for packages aziot-edge and moby-engine

**Comment by oising** [comment]
> Ask Bill to buy some disks from Amazon ;-)

No need! His 5G vaccine is turning everybody with a phone into supplementary Azure bio-blob storage! I wonder what files I'm infected with? Exciting!

**Comment by rvResolving** [comment]
> It does not find anything. I also tried the strings `msodbcsql17` and so on, still nothing is being found.

@tappoz i don't know for msodbcsql17 i need the donet-sdk 

and  I just do `sudo snap install dotnet-sdk --classic --channel=3.1`

**Comment by tappoz** [comment]
There seems to be a common root cause to all the Microsoft `apt` repos. People is cross-referencing different GitHub issues in different `git` repositories.

**Comment by schoolytics-dev0** [comment]
Similar issues here trying to use Ubuntu packages

**Comment by felipeschneider88** [comment]
I was able to get the package using Invoke-WebRequest

`PS C:\Users\felipe> iwr https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -OutFile packages-microsoft-prod.deb`

```
PS C:\Users\felipe> dir | findstr "pac"
-a----         6/17/2021  10:31 AM           3124 packages-microsoft-prod.deb
```

**Comment by DLewisEndeavor** [comment]
This seems to be the most active thread on the issue, does anyone know if this is being tracked elsewhere by Microsoft, this is affecting our production systems and we need some sort of ETA.

**Comment by aashu-kumari-by** [comment]
> I have also started seeing this issue from 17th june,2021 morning IST timezone,
> Need to get 210 MB of archives.
> After this operation, 0 B of additional disk space will be used.
> Get:1 https://packages.microsoft.com/repos/microsoft-ubuntu-focal-prod focal/main amd64 azure-functions-core-tools-3 amd64 3.0.3568-1 [210 MB]
> It has got stuck here and not able to get the response. Kindly help in resolving the issue.
> 
> This one also i got -
> curl: (28) Failed to connect to packages.microsoft.com port 443: Connection timed out
> gpg: no valid OpenPGP data found.
> Error: Process completed with exit code 2.

@rbhanda Could you let me know when this issue will get fixed, Below is the script i am using to download the package

        curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
        sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
        sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-$(lsb_release -cs)-prod $(lsb_release -cs) main" > /etc/apt/sources.list.d/dotnetdev.list'
        sudo apt-get update
        sudo apt-get install azure-functions-core-tools-3

**Comment by Jamaxack** [comment]
Just making some noise here 😄

**Comment by hasanmanzak** [comment]
Seems to be fixed..

**Comment by timvisee** [comment]
Yes, deb's such as [dotnet-host-5.0.7-x64.deb](https://packages.microsoft.com/ubuntu/20.04/prod/pool/main/d/dotnet-host/dotnet-host-5.0.7-x64.deb) are available again.

**Comment by jostFT** [comment]
I can confirm that it is fixed now 👍 ❤️

**Comment by GiacomoNasiVarGroup** [comment]
.deb packages available again!

**Comment by rafaelcaviquioli** [comment]
Finally! Everybody on their way doing build and deployments :)

**Comment by tmikaeld** [comment]
I'm sure there'll be no congestions when hundreds or maybe thousands of machines pull large packages at the exact same time ;-)

**Comment by aashu-kumari-by** [comment]
Now i am getting this error -
Get:21 https://releases.jfrog.io/artifactory/jfrog-debs xenial/contrib amd64 Packages [3634 B]
Ign:22 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease
Err:23 https://packages.microsoft.com/ubuntu/20.04/prod focal Release
  Could not connect to packages.microsoft.com:443 (40.74.238.15), connection timed out [IP: 40.74.238.15 443]
Reading package lists...
E: The repository 'https://packages.microsoft.com/ubuntu/20.04/prod focal Release' no longer has a Release file.

**Comment by khandelwalankit04** [comment]
Still seeing an issue : The repository 'https://packages.microsoft.com/ubuntu/18.04/prod bionic Release' does not have a Release file.

**Comment by kilobyte** [comment]
Well, the speed was 58KB/s, now it's nown to 22KB/s as more machines noticed the repos are up.  But I hope a few more acoustic modems will be added to the cloud. ☺

(That's in jest — thanks for making it work again!)

**Comment by rbhanda** [comment]
Hello,
As per our infra team, you may see degraded performance but the packages should be available as of now. The original cause of this issue was because there was a regression in APT Linux repos during some feature migration work that resulted in the APT repo packages becoming unavailable on the mirrors.

**Comment by Moskovych** [comment]
Does anybody have some mirrors?

**Comment by kilasuit** [comment]
> 
> 
> Does anybody have some mirrors?

In my bathroom, yes. 
For this, unfortunately not 🙁

**Comment by kilobyte** [comment]
`apt install apt-cacher-ng` then point all machines on your site to it.  Should help if you download the same package multiple times; and it'll be good to leave the cache running even after the current performance degradation is resolved.

**Comment by kevin-olbrich** [comment]
> `apt install apt-cacher-ng` then point all machines on your site to it. Should help if you download the same package multiple times; and it'll be good to leave the cache running even after the current performance degradation is resolved.

This package is broken and has lots of bugs. Better use this:
https://packages.debian.org/buster/squid-deb-proxy

We were using apt-cacher-ng for CI and such and index files broke multiple times per week. This has also been acknowledged by the maintainers. After the switch to squid-deb-proxy, cache worked better and we never had to do any maintenance again.

**Comment by NiklasGustafsson** [comment]
I'm still seeing problems:

```
2021-06-17T15:27:24.1409046Z -- 2021-06-17 15:27:24--  https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
2021-06-17T15:27:24.1464907Z Resolving packages.microsoft.com (packages.microsoft.com)... 13.90.56.68
2021-06-17T15:27:24.1985507Z Connecting to packages.microsoft.com (packages.microsoft.com)|13.90.56.68|:443... connected.
2021-06-17T15:27:24.4294434Z HTTP request sent, awaiting response... 500 Internal Server Error
2021-06-17T15:27:24.4297105Z 2021-06-17 15:27:24 ERROR 500: Internal Server Error.
```

**Comment by iconics-pavels** [comment]
I had the same issue two hours ago with Moby. But at this moment I am able to install it. The installation was very, very slow but at the end it was completed. I am working with Ubuntu 18.04.

**Comment by AlekSi** [comment]
One can also use https://www.aptly.info for mirroring

**Comment by ygrenzinger** [comment]
Hello, at my step,  i now have:

Err:1 https://packages.microsoft.com/ubuntu/21.04/prod hirsute/main amd64 dotnet-host amd64 5.0.7-1                                                                                                               
  Could not wait for server fd - select (11: Resource temporarily unavailable) [IP: 40.65.182.21 443]
E: Failed to fetch https://packages.microsoft.com/ubuntu/21.04/prod/pool/main/d/dotnet-host/dotnet-host-5.0.7-x64.deb  Could not wait for server fd - select (11: Resource temporarily unavailable) [IP: 40.65.182.21 443]

**Comment by SudhirNune** [comment]
seems like now the Azure devops is having issue - https://status.dev.azure.com/_event/246136621

**Comment by omalleyk85** [comment]
also seeing issues downloading azure-cli content from microsofts yumrepos:     
azure-arm: [MIRROR] azure-cli-2.25.0-1.el7.x86_64.rpm: Curl error (28): Timeout was reached for https://packages.microsoft.com/yumrepos/azure-cli/azure-cli-2.25.0-1.el7.x86_64.rpm [Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds]

**Comment by HeatherLDoughty** [comment]
We are still having issues
https://packages.microsoft.com/debian/10/prod buster/main amd64 aspnetcore-runtime-2.1 amd64 2.1.28-1
[8 aspnetcore-runtime-2.1 3768 kB/21.9 MB 17%]        8183 B/s 3h 43min 46s30% [8 aspnetcore-runtime-2.1 3784 kB/21.9 MB 17%]        8183 B/s 3h 43min 44s30% [8 aspnetcore-runtime-2.1 3784 kB/21.9 MB 17%]       10.9 kB/s 2h 47min 50s30% [8 aspnetcore-runtime-2.1 3784 kB/21.9 MB 17%]       10.9 kB/s 2h 47min 50s30% [8 aspnetcore-runtime-2.1 3784 kB/21.9 MB 17%]       10.9 kB/s 2h 47min 50s30% [8 aspnetcore-runtime-2.1 3784 kB/21.9 MB 17%]       10.9 kB/s 2h 47min 50s30% [8 aspnetcore-runtime-2.1 3801 kB/21.9 MB 17%]       10.9 kB/s 2h 47min 48s30% [8 aspnetcore-runtime-2.1 3801 kB/21.9 MB 17%]       10.9 kB/s 2h 47min 48s30% [8 aspnetcore-runtime-2.1 3817 kB/21.9 MB 17%]       10.9 kB/s 2h 47min 47s30% [8 aspnetcore-runtime-2.1 3817 kB/21.9 MB 17%]       10.9 kB/s 2h 47min 47s30% [8 aspnetcore-runtime-2.1 3817 kB/21.9 MB 17%]       10.9 kB/s 2h 47min 47s30% [8 aspnetcore-runtime-2.1 3817 kB/21.9 MB 17%]       10.9 kB/s 2h 47min 47s30% [8 aspnetcore-runtime-2.1 3833 kB/21.9 MB 18%]       10.9 kB/s 2h 47min 45s30% [8 aspnetcore-runtime-2.1 3833 kB/21.9 MB 18%]       10.9 kB/s 2h 47min 45s30% [8 aspnetcore-runtime-2.1 3833 kB/21.9 MB 18%]        8183 B/s 3h 43min 38s30% [8 aspnetcore-runtime-2.1 3850 kB/21.9 MB 18%]        8183 B/s 3h 43min 36s30% [8 aspnetcore-runtime-2.1 3850 kB/21.9 MB 18%]    

The pipeline is taking hours if it will ever finish

**Comment by Coding-Enthusiast** [comment]
The servers seem to be overloaded for now but the files are indeed back when checked manually. Our [Travis-ci build](https://travis-ci.com/github/Autarkysoft/Denovo/builds/229423656) is now failing with a timeout.

**Comment by troglodytto** [comment]
Microsoft ran in an overload situation. Maybe try GCP?

**Comment by m17kea** [comment]
@rbhanda will there be an incident report in response to this? I'd be particularly interested in why mirror sites were not available or if available, why there is a single point of failure affecting them all.  We've faced issues in the past where packages would fail when a deployment was running but a cataclysmic failure of this nature would have affected many production workloads today. Package managers are the backbone of our industry and we need to be able to rely on them. I've been forced to remove reliance on Microsoft package repos in favour of self hosted ones for the time being which is unnecessary manual maintenance I'd like to avoid if possible. Will there be an issue I can track on Microsoft adding reliable resilience to these services? Also, are there any status pages I can refer to going forward on these services?

**Comment by ra-om** [comment]
Have This Issue, I Also +1

**Comment by mikevo13** [comment]
> @rbhanda will there be an incident report in response to this? I'd be particularly interested in why mirror sites were not available or if available, why there is a single point of failure affecting them all. We've faced issues in the past where packages would fail when a deployment was running but a cataclysmic failure of this nature would have affected many production workloads today. Package managers are the backbone of our industry and we need to be able to rely on them. I've been forced to remove reliance on Microsoft package repos in favour of self hosted ones for the time being which is unnecessary manual maintenance I'd like to avoid if possible. Will there be an issue I can track on Microsoft adding reliable resilience to these services? Also, are there any status pages I can refer to going forward on these services?

Agree, this is the 3rd time we have encountered this issue, and Microsoft does not seem care.

**Comment by kevin-olbrich** [comment]
> > @rbhanda will there be an incident report in response to this? I'd be particularly interested in why mirror sites were not available or if available, why there is a single point of failure affecting them all. We've faced issues in the past where packages would fail when a deployment was running but a cataclysmic failure of this nature would have affected many production workloads today. Package managers are the backbone of our industry and we need to be able to rely on them. I've been forced to remove reliance on Microsoft package repos in favour of self hosted ones for the time being which is unnecessary manual maintenance I'd like to avoid if possible. Will there be an issue I can track on Microsoft adding reliable resilience to these services? Also, are there any status pages I can refer to going forward on these services?
> 
> Agree, this is the 3rd time we have encountered this issue, and Microsoft does not seem care.

That's nothing new and has always been working like that. This applies to many of their products and services.
You always need an alternative handy (which is always a good idea, not just when working with MS).

**Comment by satyamravindra** [comment]
We had an incident with packages.microsoft.com that resulted in packages being unavailable. Our engineering team has mitigated the issue and our internal data shows improvement in the availability. If you still have problems, please provide us more information (output of "apt-get update|install") and we can investigate it further.

**Comment by Uter1007** [comment]
Install azure-cli is also very slow when downloading it via official scripts: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

**Comment by stromcon** [comment]
![image](https://user-images.githubusercontent.com/6690149/122472796-549ac900-cfc1-11eb-8178-2bf81b1025fa.png)

Same for me, downloads are very slow from packages.microsoft.com

**Comment by dazfuller** [comment]
This is what I'm seeing at the moment

```
Get:1 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 odbcinst amd64 2.3.7 [12.0 kB]
Err:2 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 unixodbc-dev amd64 2.3.7
  Connection failed [IP: 13.90.21.104 443]
Get:3 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 odbcinst1debian2 amd64 2.3.7 [135 kB]
Err:4 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 libodbc1 amd64 2.3.7
  Could not wait for server fd - select (11: Resource temporarily unavailable) [IP: 13.90.21.104 443]
```

**Comment by leecow** [comment]
Sorry for all of the issues and inconveniences this has caused! I just saw a report from the team that owns packages.microsoft.com and here's a summary of where they're at:

* West US mirrors will be up very soon (if not already done), which should begin to alleviate some of the performance issues.
* Mirrors in Europe online in ~5 hours (currently replicating), which will address the latency in Europe and further help the US responsiveness by reducing the load.

**Comment by Mlocik97** [comment]
Don't spy on users (I'm looking on You Win10) and You will have a lot of free space on disks.

**Comment by bb980701** [comment]
From Europe behind a proxy impossible to download   few byte/s
![image](https://user-images.githubusercontent.com/71716559/122478583-f9210900-cfc9-11eb-97a3-86a4987436ff.png)

**Comment by stromcon** [comment]
Using a VPN and `ipconfig /flushdns` i was able to download azure cli since europe still down

**Comment by abhishek179** [comment]
apt-get fails to get the package from this repo.
Get:1 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 blobfuse amd64 1.3.7 [7,195 kB].


Is this a known issue that is getting worked upon?

**Comment by thedimas3007** [comment]
Now it works

**Comment by abhishek179** [comment]
yeah it is still slow(intermittently) but working..

**Comment by aashu-kumari-by** [comment]
Yeah ours is running only from last 2 hours not sure when it will complete :( @rbhanda  Please let me know when we can expect this to be completely working.

**Comment by dimanchezzz** [comment]
This solution helped for me
`snap install dotnet-sdk --classic`

**Comment by m17kea** [comment]
I don't think it is appropriate for Microsoft to proclaim to the world in their own [health dashboards](https://status.dev.azure.com) and [event trackers](https://status.dev.azure.com/_event/246136621) that all is well, when these services are still clearly degraded.

**Comment by aashu-kumari-by** [comment]
> Yeah ours is running only from last 2 hours not sure when it will complete :( @rbhanda Please let me know when we can expect this to be completely working.

Now i can confirm its running fine, but yeah we need to monitor it for few more times.
Thanks

**Comment by Mlocik97** [comment]
I'm just downloading code update and it's ~500kbps so slow.....

**Comment by Uter1007** [comment]
60kb/sec for the azure-cli :( Still hope that microsoft will fix their slow connection for ubuntu repositories.

**Comment by ravindrabhartiya** [comment]
Confirming the incident resolution at 10:17PM PST last night. We have restored the service in all regions, been monitoring the results since resolution and got confirmation from multiple customers that they no longer observe the issue. Thank you for reporting this issue.

**Comment by tksrc** [comment]
Hey guys,

I am still having issues interacting with the repo... 

`#10 6.790 deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ hirsute main
#10 6.961 Hit:1 http://archive.ubuntu.com/ubuntu hirsute InRelease
#10 7.009 Hit:2 http://archive.ubuntu.com/ubuntu hirsute-updates InRelease
#10 7.070 Hit:3 http://archive.ubuntu.com/ubuntu hirsute-backports InRelease
#10 7.096 Hit:4 http://security.ubuntu.com/ubuntu hirsute-security InRelease
#10 7.156 Ign:5 https://packages.microsoft.com/repos/azure-cli hirsute InRelease
#10 7.215 Err:6 https://packages.microsoft.com/repos/azure-cli hirsute Release
#10 7.215   404  Not Found [IP: 13.81.215.193 443]
#10 7.306 Reading package lists...
#10 7.837 E: The repository 'https://packages.microsoft.com/repos/azure-cli hirsute Release' does not have a Release file.
------
executor failed running [/bin/sh -c DEBIAN_FRONTEND="noninteractive"  apt-get install -yq ca-certificates curl apt-transport-https lsb-release gnupg         && curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null         && AZ_REPO=$(lsb_release -cs)         && echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | tee /etc/apt/sources.list.d/azure-cli.list         && apt-get update         && apt-get install -yq azure-cli         && apt-get clean]: exit code: 100`

**Comment by tksrc** [comment]
My bad... I was using ubuntu 21.04 (hirsute). I noticed that version is not yet supported (doesn't exist) in the repo: https://packages.microsoft.com/repos/azure-cli/dists/

Switched back to 20.04 (focal) and it worked. 

Thanks

**Comment by michaelgsharp** [comment]
Closing since the issue has been resolved.

**Comment by MinzigesTV** [comment]
```
pi@raspberrypi:~ $ sudo apt-get install -y dotnet-runtime-5.0
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package dotnet-runtime-5.0
E: Couldn't find any package by glob 'dotnet-runtime-5.0'
E: Couldn't find any package by regex 'dotnet-runtime-5.0'
```

It somehow does not work...

**Comment by janekska** [comment]
> 
> 
> ```
> pi@raspberrypi:~ $ sudo apt-get install -y dotnet-runtime-5.0
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> E: Unable to locate package dotnet-runtime-5.0
> E: Couldn't find any package by glob 'dotnet-runtime-5.0'
> E: Couldn't find any package by regex 'dotnet-runtime-5.0'
> ```
> 
> It somehow does not work...

+1 
still the same problem for me too

Used these receipes:
https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#2004-
and
https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#apt-troubleshooting

**Comment by xTEddie** [comment]
I am having trouble install `az` package

![image](https://user-images.githubusercontent.com/8888565/128944903-61637744-eb54-48cd-9148-79243a2a6761.png)

**Comment by ijnek** [comment]
@xTEddie That issue is probably related to the packages.microsoft.com outage that has happened today. See #6560.

**Comment by noxish** [comment]
cannot install dotnet5 on ubuntu, is this still a problem?

**Comment by janekska** [comment]
Solved by manual install.

Brgds

Stefano Hämmerle ***@***.***> (šajā datumā: pirmd., 2021. g.
30. aug. 12:11) rakstīja:

**Comment by dralley** [comment]
@rbhanda What is the correct place to file issues with repositories located at https://packages.microsoft.com/?

Specifically, I have noticed some issues with https://packages.microsoft.com/rhel/8/prod/, but I have not been able to find the correct venue to report them.

**Comment by rbhanda** [comment]
Hello @dralley as of now we do not have a repository for  https://packages.microsoft.com/ on GitHub. Until we have one, if you are facing any issues, I recommend to create them on https://github.com/dotnet/core/issues

**Comment by Phatkone** [comment]
I know this thread is old but I am still seeing this issue with 20.04

`Ign:6 https://packages.microsoft.com/config/ubuntu/20.04/prod focal InRelease
Err:7 https://packages.microsoft.com/config/ubuntu/20.04/prod focal Release
  404  Not Found [IP: 40.65.182.21 443]
Reading package lists... Done
E: The repository 'https://packages.microsoft.com/config/ubuntu/20.04/prod focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.`

surely a company with as much resource as Microsoft could fix an issue like this and not take 4 months to do so?

**Comment by hrai** [comment]
I'm on `Ubuntu Impish 20.10`.

The command given at https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#2110- refers to `20.10`

![image](https://user-images.githubusercontent.com/4055444/141042632-6392ae6c-1cb6-420c-934a-56cfb0883472.png)

But when I go to https://packages.microsoft.com/config/ubuntu/, there's no `20.10`

![image](https://user-images.githubusercontent.com/4055444/141042759-b2ecdd0f-c875-40ca-8210-1f940f4c5c58.png)

I had to change the command to below:
```
wget https://packages.microsoft.com/config/ubuntu/21.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
rm packages-microsoft-prod.deb
```

Then it worked like a charm.

Perhaps before pushing out documentation, it would be good to test and verify the commands in them.

**Comment by mairaw** [comment]
@hrai it would be great if you open feedback for the doc in question. There's a feedback button on the bottom of the page. /cc @adegeo

**Comment by adegeo** [comment]
To close the loop, this was updated in the doc: using the 21.04 repository is the current guidance.

**Comment by jean-paullizotte** [comment]
Itt seems it's still problematic this morning. Both Azure Devops pipelines are taking an eternity to download Packages and on my workstation too (avg 85kb/s)

**Comment by jnt2007** [comment]
Reproduces for me on Ubuntu 24
```
Ign:50 https://packages.microsoft.com/repos/azure-cli noble InRelease                                                                                                                                      
Ign:51 https://packages.microsoft.com/repos/code stable InRelease
Ign:50 https://packages.microsoft.com/repos/azure-cli noble InRelease
Ign:51 https://packages.microsoft.com/repos/code stable InRelease
Ign:50 https://packages.microsoft.com/repos/azure-cli noble InRelease
Ign:51 https://packages.microsoft.com/repos/code stable InRelease
Err:50 https://packages.microsoft.com/repos/azure-cli noble InRelease
  Could not wait for server fd - select (11: Resource temporarily unavailable) [IP: 13.107.213.45 443]
Err:51 https://packages.microsoft.com/repos/code stable InRelease
  Could not wait for server fd - select (11: Resource temporarily unavailable) [IP: 13.107.213.45 443]
```
