### ISSUE TITLE
packages.microsoft.com are super slow

### ISSUE THREAD

**Issue by jean-paullizotte** [dotnet/core#7625]
The repo seems problematic this morning. Both Azure Devops pipelines are taking an eternity to download Packages and my workstation too (avg 85kb/s)

Code to reproduce:

```
wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb

sudo apt-get update
sudo apt-get install azure-functions-core-tools-3
```

![image](https://user-images.githubusercontent.com/36302005/180265310-7dc953eb-ea72-4e33-921f-98b0d452444f.png)

**Comment by rbhanda** [comment]
https://github.com/microsoft/linux-package-repositories/issues/13 related issue.

We are looking into this right now.

**Comment by h4de5** [comment]
some problem here.

![image](https://user-images.githubusercontent.com/6115324/180412181-af2cd9ee-a2c2-4a21-b0b9-8a546cb5d774.png)

some pipelines run into a time out due to this.

**Comment by rbhanda** [comment]
closing since this issue has been resolved https://github.com/microsoft/linux-package-repositories/issues/13

**Comment by pkumarg** [comment]
Facing slow down, I see two threads related to this problem, both are closed. But problem still exists.

<img width="2419" height="784" alt="Image" src="https://github.com/user-attachments/assets/8e28bdaa-4953-43d4-ba33-b94c7835d6c0" />

**Comment by rbhanda** [comment]
> Facing slow down, I see two threads related to this problem, both are closed. But problem still exists.
> 
> <img alt="Image" width="2000" height="784" src="https://private-user-images.githubusercontent.com/31144474/526390699-8e28bdaa-4953-43d4-ba33-b94c7835d6c0.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjU4MDYzOTIsIm5iZiI6MTc2NTgwNjA5MiwicGF0aCI6Ii8zMTE0NDQ3NC81MjYzOTA2OTktOGUyOGJkYWEtNDk1My00M2Q0LWJhMzMtYjk0Yzc4MzVkNmMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjE1VDEzNDEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkOGE1ZDRmZDRjNjI1ZjNmNjllZWUyMDcyMTFiNzRmYzAwNjFkMWRlYThjZDA5YzY4YjI4Yjk0MWJmNGU5OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KZlTSkS_vK-d-nejD-cF0qOI8A45I_7B8MlbIb1c2rc">

https://github.com/microsoft/linux-package-repositories/issues/291 - I have created an issue for you in the repository for the team who can help look into this

**Comment by acheng-01** [comment]
@pkumarg Are you still experiencing performance issues? Please see [my colleague's comment](https://github.com/microsoft/linux-package-repositories/issues/291#issuecomment-3655844987). We will need some additional information from you to help troubleshoot. I've queried a couple of metrics from our Azure Frontdoor profile that's in charge of our caching and content delivery. So far I don't see that we've had any performance decline in the past 24 - 48 hours across all of our PoPs.
