### ISSUE TITLE
azureedge tracking issue

### ISSUE THREAD

**Issue by richlander** [dotnet/core#9674]
We are making many changes due to `azureedge.net` domains no longer being supported/available, per https://github.com/dotnet/core/issues/9671.

Tracking issues:

- https://github.com/dotnet/install-scripts/issues/559
- https://github.com/dotnet/core/issues/9669
- https://github.com/dotnet/core/issues/9673
- https://github.com/dotnet/dotnet-docker/pull/6125
- https://github.com/actions/setup-dotnet/issues/570

**Comment by allschu** [comment]
I don't know exactly what is going on the last few days, but we have a very hard time in reaching  https://dot.net/v1/dotnet-install.sh from our Bitbucket pipelines. 

```
+ curl -sSL https://dot.net/v1/dotnet-install.sh --output dotnet-install.sh

curl: (56) Recv failure: Connection timed out
```
Could this be part of this issue?

**Comment by baronfel** [comment]
The .NET Website uses a different routing infrastructure before it gets to the new CDN urls - see https://github.com/dotnet/install-scripts/issues/582#issuecomment-2749567858 for more details. I though this was resolved already, but can investigate with the internal team that controls this infra for us again.

**Comment by mairaw** [comment]
My monitoring is alerting that the redirection service is still having issues. I contacted the team again.

**Comment by allschu** [comment]
Yes please, thank you

**Comment by richlander** [comment]
We have a backlog item to switch redirection services. We are planning on moving to Azure Front Door.
